name: '🐛 Bug Report'
description: Report errors and problems
labels: [bug]
body:
  - type: input
    id: plugin-version
    attributes:
      label: '🎆 Advanced Achievements version'
      description: 'What version of the plugin are you running?' 
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: '🖥 Server version'
      description: 'What server version are you running?' 
    validations:
      required: true

  - type: checkboxes
    id: issues-searched
    attributes:
      label: '📁 Existing issues'
      description: 'Many new issues tend to be duplicates, have you searched [existing ones](https://github.com/mrfdev/advanced-achievements/issues)?'
      options:
        - label: 'I have searched existing issues.'
          required: true

  - type: textarea
    id: description
    attributes:
      label: '🐛 Description'
      description: 'A clear and concise description of the problem, including any steps to reproduce.'
    validations:
      required: true

  - type: textarea
    id: server-logs
    attributes:
      label: '📄 Server logs'
      description: 'If there are any relevant server logs or exceptions, please paste them between the ``` lines below.'
      value: |
        ```
        
        ```
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: '⚙ Configuration'
      description: 'Please paste relevant configuration sections between the ``` lines below. (If you have changed it from default)'
      value: |
        ```
        
        ```
    validations:
      required: false
