name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build project
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: AdvancedAchievements
          path: advanced-achievements-plugin/target/advanced-achievements-plugin-7.2.0.jar