name: Build Plugin

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.9.8
      - name: Build project
        run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          name: AdvancedAchievements
          path: advanced-achievements-plugin/target/${project.build.finalName}.jar

