name: Compare Config Files and Create PR

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  compare-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download config.yml from 1MB repository
        run: |
          curl -sSL -o config-1mb.yml https://raw.githubusercontent.com/mrfdev/1MB/master/Resources/AdvancedAchievements/config.yml

      - name: Compare to local config.yml
        id: compare
        run: |
          if ! diff -q config-1mb.yml advanced-achievements-plugin/src/main/resources/config.yml > /dev/null; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
            cp config-1mb.yml advanced-achievements-plugin/src/main/resources/config.yml
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request if files differ
        if: steps.compare.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Sync config.yml with 1MB repository'
          body: 'This PR updates `config.yml` to match the version from the 1MB repository.'
          commit-message: 'Update config.yml from 1MB repo'
          base: master
          branch: sync-config