name: Compare Config Files and Create PR

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  compare-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download and compare with 1MB config
        id: compare
        run: |
          TMP_FILE="advanced-achievements-plugin/src/main/resources/config-remote.yml"
          TARGET_FILE="advanced-achievements-plugin/src/main/resources/config.yml"

          curl -sSL -o "$TMP_FILE" https://raw.githubusercontent.com/mrfdev/1MB/master/Resources/AdvancedAchievements/config.yml

          if ! diff -q "$TMP_FILE" "$TARGET_FILE" > /dev/null; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
            mv "$TMP_FILE" "$TARGET_FILE"
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
            rm "$TMP_FILE"
          fi

      - name: Create Pull Request if files differ
        if: steps.compare.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Sync config.yml with 1MB repository'
          body: 'This PR updates `config.yml` to match the latest version from the 1MB repository.'
          commit-message: 'Update config.yml to match 1MB repository'
          base: master
          branch: sync-config